- setup.py
Without this change, the setup.py build will result in
Traceback (most recent call last):
File "setup.py", line 19, in <module>
LONG_DESCRIPTION = open(readme).read()
IOError: [Errno 2] No such file or directory: 'README'
> Fix setup.py build failure

- fake_filesystem.py
- fake_filesystem_test.py
If you were to call rename() with the same values for both old name and new
name, GetEntry would raise an unnecesary KeyError. This commit fixes that.
Here's the traceback of the bug:
```
renamer.py:73: in run
os.rename(i, o)
../.virtualenvs/renamer/lib/python2.7/site-packages/fake_filesystem.py:1566: in rename
old_object = old_dir_object.GetEntry(old_name)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <fake_filesystem.FakeDirectory object at 0x6fffee1ce10>, pathname_name = 'eggs'
def GetEntry(self, pathname_name):
"""Retrieves the specified child file or directory.
Args:
pathname_name: basename of the child object to retrieve
Returns:
string, file contents
Raises:
KeyError: if no child exists by the specified name
"""
>     return …
```
> Fix bug with calling rename with equal old & new names.

- fake_filesystem.py
- fake_filesystem_test.py
- fake_filesystem_vs_real_test.py
To be more specific, I had errors with `os.path.realpath`. As it turned out, cygwin wasn't recognized as a Windows and thas was causing the errors.
This commit should fix most of other undiscovered issues with cygwin.
Also, it's better to keep the critical logic of recognizing the system in a single place.
> Treat cygwin as a Windows

- fake_filesystem_unittest.py
`Stubber` class was instantiating `FakePathModule` directly, without passing `os_module` argument. FakePathModule docstring states that such behavior is deprecated.
> Fix FakePathModule deprecation in Stubber

- fake_filesystem.py
- fake_filesystem_test.py
- fake_tempfile_test.py
This also works for non-Unicode encodings (like compressed data).  
It fixes an expected behavior on Python 3 where reading strings from a binary file opened in non-binary mode will raise an exception.
> Protect binary data a little better

- fake_tempfile_test.py
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_tempfile.py
This promotes the FakeFileWrapper class to top-level and has mkstemp wrap its file.  This lets fdopen() work properly.  This should address #23 (among other things).
> Wrap file created by mkstemp

- fake_filesystem_test.py
- pyfakefs/fake_filesystem.py
So block devices aren't accidentally considered directories.  Should address #24.
> Use proper checking for directory on open.

- fake_filesystem_test.py
- pyfakefs/fake_filesystem.py
mtime and ctime are updated during the SetContents() methods.
Removes a change to ctime that occurred just before that.
FakeFilesystem gets an `float_stat` option, that updates stat time
to the full precision of the time.time() call. The existing behavior,
using integers, is preserved as the default.
> Writes update mtime and float time support

- fake_filesystem_test.py
- pyfakefs/fake_filesystem.py
- correctly handle drive root in SplitPath() (hopefully last fix )
> Drive letter handling fix

- fake_filesystem_test.py
- pyfakefs/fake_filesystem.py
This change adds support for hard links, and tests to go along with
that.
There is a bit of ugliness in this change around the use of the name
field on FakeFile instances. Support for hard links means that the same
file can have different names under different directories, so it
fundamentally doesn't make sense for FakeFile instances to have a name
associated with them.
However, I didn't want to have to perform a mass refactoring as a
prerequisite to making this change, so it instead just sets the filename
as needed to work with the existing implementation of AddObject. This
has the unavoidable side effect of changing the name associated with the
original file as well, since they share the same FakeFile instance.
It looks like this is probably safe to do now, but to properly ensure
that …
> Implement hard link support

- fake_filesystem_test.py
- pyfakefs/fake_filesystem.py
- changed to not rely on file name member as this may be incorrect in
case of hard links
- re-enabled tests under Windows
> Fixed NormalizeCase() with hard links

- fake_filesystem_unittest_test.py
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_filesystem_unittest.py
- redirects to FakeFileOpen
- fixes #70 and #103
> Fake io open

- fake_filesystem_shutil_test.py
- fake_filesystem_test.py
- fake_tempfile_test.py
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_tempfile.py
- raise on file deletion if missing write permission
- raise on deleting an open file under Windows
- make sure check is done recursively if deleting directories
- fixes #27
> Handle file permissions on deletion

- pyfakefs/fake_filesystem_unittest.py
- added possibility to add own skipnames in derived test class
- fixes #104
- can be used to fix #106
> Removed shutil from SKIPNAMES

- fake_filesystem_test.py
- fake_tempfile_test.py
- pyfakefs/fake_filesystem.py
- save file contents always as bytes
- consider encoding parameter in open() / io.open()
- use locale prefered encoding instead of utf-8 as default encoding
- fixes #120
> Added support for file encoding

- fake_filesystem_shutil_test.py
- fake_filesystem_test.py
- pyfakefs/fake_filesystem.py
Support for links was added to Windows in Python 3.2.  When attempting to create a symbolic or hard link on an earlier Python version, raise an exception.
@mrbean-bremen, please review.
> Raise OSError if on Windows before Python 3.2.

- pyfakefs/fake_filesystem_glob.py
- use sources from Python 3.5, slightly adapted to work under Python 2
and use fake file system
- fixes #59 and #116
> Added support for glob.iglob and recursive flag

- .travis.yml
- fake_filesystem_test.py
- pyfakefs/fake_filesystem.py
- enabled encoding tests for Python 2 using u literal
- fixed incorrect encoding for writing files under Python 2
> Removed Python 3.2, added 3.6 tests in travis config

- README.md
- fake_filesystem_test.py
The only change I made here is to recognize in the tests that on OSX ~root
is /var/root instead of /root.
setup.py has claimed OSX support all along, which is basically true.
@mrbean-bremen, sanity check, please.
> Update tests to pass on OSX; update README to claim OSX support

- fake_filesystem_unittest_test.py
- pyfakefs/fake_filesystem_unittest.py
- can be set to False to avoid patching 'path' (see #53)
- added optional argument to TestCase constructor to set it
> Added class attribute Patcher.patch_path

- fake_filesystem_test.py
- fake_pathlib_test.py
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_pathlib.py
- raise NotADirectoryError where needed so it raised by os.readlink
- made pathlib resolve() conform to real implementation
- added strict argument to resolve in Python 3.6
- made some fake_pathlib functions available only in 3.5 as in the ral
implementation
> Error handling fixes

- fake_filesystem_shutil_test.py
- fake_filesystem_test.py
- fake_pathlib_test.py
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_pathlib.py
- renamed supports_drive_letter to is_windows_fs and use it for more Windows-specific stuff to be able to run more tests for Windows fs under Linux
- added Windows/Posix variants for some tests that ran only under one system before
- test for raised OSError subtypes 
- faek_pathlib_test: used uncommon path separator to ensure usage of fake filesystem
- use SplitPath instead of os.path.split in RenameObject()
> Improved support for Windows file system tests

- fake_filesystem_test.py
- pyfakefs/fake_filesystem.py
Hi,
I found a bug on the os.listdir expected behaviour in python 3.5 (I'm migrating a project from 2.7 to 3.5).
os.listdir on a fake directory returns a dictionnary instead of a list.
I fixed it in the pull request by returning the list of keys if it's a dictionnary. Maybe not the best but I don't know the library enought to dig further.
Kind Regards,
Alexis
> os.listdir sometime returns a dict instead of a list

- fake_filesystem_shutil_test.py
- pyfakefs/fake_filesystem_shutil.py
If both the source and destination argument of shutil.move are
directories the source directory is copied under the target directory.
pyfakefs implementation copied the source directory to the target
directory.
The real shutil.move call shutil.copy('/path/to/src', '/path/to/dest')
moves /path/to/src to /path/to/dest/src but the pyfakefs implementation
moved the src directory to /path/to/dest
> Fix shutil.move implementation

- CHANGES.md
- fake_filesystem_test.py
- fake_filesystem_vs_real_test.py
- pyfakefs/fake_filesystem.py
- adapted some tests to use an arbitrary path separator to make sure we
use the defined separator
- faked split(), dirname(), walk(), realpath(), adapted relpath() to fix these tests
- fixed case sensitivity for cygwin
> Windows test related changes

- CHANGES.md
- fake_filesystem_test.py
- fake_filesystem_unittest_test.py
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_filesystem_unittest.py
This copies a file from the real file system to
the fake file system, making it easy to use
files from the real file system in your tests.
@mrbean-bremen, please review.
> Added helper method fake_filesystem_unittest.TestCase.copyRealFile()

- CHANGES.md
- fake_filesystem_unittest_test.py
- pyfakefs/fake_filesystem_unittest.py
- do not test the whole string contents as this will not work with other line endings (e.g. on Windows)
- moved setUpClass() code into class as setUpClass() is not available under Python 2.6
> Minor changes to copyRealFile

- fake_filesystem_test.py
- pyfakefs/fake_filesystem.py
Previously if you created file having larger initial contents than the
free space in the fake filesystem, the disk usage counter was decreased
by the size of the initial contents possibly resulting in negative usage.
Basically the issue was that when ChangeDiskUsage is called with size
larger than the amount of free space, space usage is not changed but
an error is raised. Due to an exception, CreateFile removes the created
object that results in new call to ChangeDiskUsage with negative size
of the object.
Previously the object's size was set before ChangeDiskUsage was called
and then when the object was being removed the object's already set size
was used to reduce the filesystem usage (even though that size was never
added to the usage).
> Fix disk usage calculations when too large file is created

- fake_filesystem_unittest_test.py
- pyfakefs/fake_filesystem_unittest.py
Updated the documentation to clarify this issue.  @mrbean-bremen, please review using your knowledge of file systems.
This problem manifests on MacOS because it updates atime, whereas Linux and Windows do not.
Because this is not a functional change, I did not add this issue to the release notes.
> Correct test to properly test copyRealFile() atime on MacOS

- fake_filesystem_test.py
SetLargeFileSizeTest should derive directly from unittest.TestCase instead
of FakeDirectoryUnitTest, to avoid running tests in FakeDirectoryUnitTest
twice.
> Derive SetLargeFileSizeTest directly from TestCase

- fake_filesystem_test.py
This base class has no tests, and all other non-concrete test case base classes
in this file use a *TestBase convention.
..small cleanup for your consideration.
> Rename PathManipulationTests to PathManipulationTestBase for consistency

- fake_filesystem_unittest_test.py
- pyfakefs/fake_filesystem_unittest.py
Changed TestCase.copyRealFile to default the value of fake_file_path to the same value as real_file_path, when fake_file_path is not provided/None.
> copyRealFile fake_file_path defaults to real_file_path

- fake_filesystem_unittest_test.py
- fixtures/module_with_attributes.py
- pyfakefs/fake_filesystem_unittest.py
One of my modules has a `path` attribute, and I was dismayed to find that it got patched.
This branch takes extra care to patch only modules.
Code review please, @mrbean-bremen.
> Patch only modules with fake_filesystem_unittest.Patcher

- CHANGES.md
- example.py
- example_test.py
- fake_filesystem_test.py
- fake_filesystem_unittest_test.py
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_filesystem_unittest.py
- allow to add really existing files and directory trees to the fake
file system, with the contents read on demand
- see #170
> Added methods to access real files

- CHANGES.md
- fake_filesystem_shutil_test.py
- pyfakefs/fake_filesystem.py
> Normalize file path in RemoveObject()

- fake_filesystem_test.py
- pyfakefs/fake_filesystem.py
- real directory contents are only added to the fake file system on
demand (makes adding large directory trees faster)
- refactored real file/directory access to use own classes
> Added lazy evaluation of real directories

- CHANGES.md
- fake_filesystem_test.py
- pyfakefs/fake_filesystem.py
- added support for O_RDONLY, O_WRONLY, O_RDWR, O_APPEND, O_TRUNC and O_EXCL (O_CREAT was already implemented)
- added support for opening directories read-only for Posix systems
- fixes #204
> Added support for basic modes in os.open()

- CHANGES.md
- fake_filesystem_test.py
- pyfakefs/fake_filesystem.py
- fixed assertRaisesIOError and assertRaisesOSError
- never allow adding of already existing file or directory
- fixes #203
> Raise exception if trying to create file in read-only directory

- CHANGES.md
- fake_filesystem_test.py
- pyfakefs/fake_filesystem.py
- tox.ini
- fixed handling of symlinks in MakeDirectories()
- fixed exception thrown on too many symlinks
- see #209
> Fixed handling of invalid parent paths in CreateDirectory()

- README.md
> Adapted usage scenarios in README

- fake_filesystem_test.py
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/fake_pathlib.py
- pyfakefs/fake_scandir.py
- refactored Patcher for easier possibility to add new modules
- moved fake scandir implementation into separate module and use it both for os.scandir and scandir.scandir
- shall fix #332
> Added support to fake out the backported scandir

- pyfakefs/fake_filesystem_unittest.py
Solves issue #334, which is caused by `DynamicPatcher` deleting stuff from `sys.modules` during its initialization.
> Only construct DynamicPatcher if necessary

- pyfakefs/fake_filesystem_unittest.py
- tests/fake_filesystem_unittest_test.py
- tests/fake_os_test.py
This PR splits TestCase into TestCaseMixin and TestCase. The TestCaseMixin class can be used with other than unittest.TestCase TestCase classes (for example, django.test.TestCase or asynctest.TestCase)
> Test case mixin

- .travis/run_tests.sh
* FileNotFoundError, FileExistsError, NotADirectoryError exist in Python 3 but [not in Python 2](https://travis-ci.org/jmcgeheeiv/pyfakefs/jobs/344658535#L479-L512).
* file(), long, unicode exist in Python 2 but [not in Python 3](https://travis-ci.org/jmcgeheeiv/pyfakefs/jobs/344658538#L475-L502).
> Add flake8 to testing

- pyfakefs/fake_filesystem.py
- pyfakefs/helpers.py
- tests/fake_filesystem_unittest_test.py
The _try: except NameError:__ approach follows the Python porting best practice [Use feature detection instead of version detection](https://docs.python.org/3/howto/pyporting.html#use-feature-detection-instead-of-version-detection) and keeps the linters at bay.
The alternative approach uses the very popular [six](http://six.readthedocs.io) module instead.
> Fix undefined names in Python3

- pyfakefs/fake_filesystem_shutil.py
This removes an unnecessary shebang line from `fake_filesystem_shutil.py`, as
this file is a Python module and isn't invoked via CLI.
> Remove unnecessary shebang line

- pyfakefs/fake_filesystem.py
- pyfakefs/tests/fake_os_test.py
- made the handling even more complicated due to different behavior for different OSes
- fixes #373 and #374
> Added more OS specific handling for file paths ending with separator

- pyfakefs/fake_filesystem.py
- pyfakefs/tests/fake_os_test.py
> Fixed regression for isDir() with trailing separator under MacOS

- pyfakefs/fake_filesystem.py
- pyfakefs/tests/fake_os_test.py
> Added special handling for broken symlinks with trailing separators

- pyfakefs/helpers.py
- pyfakefs/tests/fake_open_test.py
Using `readline()` on a binary file may throw an exception in the Python3 environment; and some standard Python libraries do that, most notably `pickle.load()`. The problem is that binary contents should not be decoded and at the same time all EOL searches should use `bytes` form of the EOL sequence.
> binary readline (Py3) fixed

- .travis/run_pytest.sh
- appveyor.yml
- pyfakefs/pytest_plugin.py
- pyfakefs/tests/pytest_check_failed_plugin_test.py
- pyfakefs/tests/pytest_plugin_failing_test.py
- does not work for Python 3.3 (which should not be used anymore anyway)
- see #381
> Make sure that the linecache module is not using the fake file system

- CHANGES.md
- pyfakefs/fake_filesystem.py
- pyfakefs/tests/fake_os_test.py
- added support for reading/writing arbitrary extended attributes
(Linux / Python 3 only)
- Note: support for extended fs attributes is assumed, not checked
- see #423
> Added some support for extended filesystem attributes

- CHANGES.md
- docs/usage.rst
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- path is only patched if it is os.path (detected by name)
> Removed patch_path argument from UnitTest and Patcher

- .travis.yml
- .travis/install.sh
- CHANGES.md
- README.md
- appveyor.yml
- docs/intro.rst
- setup.py
- added 3.7 builds for MacOS and Windows
- use released 3.7 build for Linux
- closes #436
> Remove support for Python 3.3

- pyfakefs/fake_filesystem.py
- pyfakefs/tests/fake_filesystem_test.py
**Background:**
On linux, parts of the file system have other uses than being actual files. One example is "/sys/class/gpio".
To mock the expected behaviour in this example a "side effect" of writing to the files is needed:
1. When writing an int XX to "/sys/class/gpio/export" a new directory is created "/sys/class/gpio/gpioXX" with some files
2. when writing an int XX to "/sys/class/gpio/unexport" the directory "/sys/class/gpio/gpioXX" is removed.
This "side effect" needs to happen in the same way during testing as in real environment to not affect the SUT. For example, if the folder "/sys/class/gpio/gpioXX" is created in the setup of the test the SUT can see that gpioXX is already available and skip writing to "/sys/class/gpio/export".
Another solution could have been polling the files …
> Add side_effect option to fake files

- pyfakefs/pytest_plugin.py
`python-future` is notorious for breaking modules which use `try:` / `except:`
to import modules based on version.  In this case, `pyfakefs` imported the
backported `builtins` module which changes the semantics of the `open()`
function.  `pyfakefs` then monkeypatches `linecache` which breaks any module
which attempts to use `linecache` (in this case `pytest`).
The downstream issue is https://github.com/pytest-dev/pytest/pull/4074
> Fix pytest when pyfakefs + future is installed

- CHANGES.md
- docs/usage.rst
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_filesystem_shutil.py
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/fake_pathlib.py
- pyfakefs/fake_scandir.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- pyfakefs/tests/import_as_example.py
- allows imports like 'from os import stat' to be patched
> Automatically patch imported functions

- CHANGES.md
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/helpers.py
- pyfakefs/pytest_plugin.py
- pyfakefs/tests/example.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- pyfakefs/tests/import_as_example.py
- in Python 2, builtin open is now handled by FakeBuiltinModule 
- in Python 3, builtin open is handled via io.open
- adapted pytest plugin to ensure that open is not patched
for linecache and dependent tokenize modules
- importing builtin open as other name does not work with PyPy2
- see #449
> Added automatic patching of builtin open as other name

- pyfakefs/fake_filesystem.py
Changed argument name in `FakeIOModule.open` from `file_name` to `file`.
It makes pyfakefs compatible with the library atomicwrites that uses `kwargs` to pass arguments to `io.open` function.
See https://github.com/untitaker/python-atomicwrites/blob/890e7aed4a1fd3b3724dc64503757617996c3978/atomicwrites/__init__.py#L180
In python documentation argument is also named `file`:
py3: https://docs.python.org/3/library/functions.html#open
py2: https://docs.python.org/2.7/library/io.html#io.open
> FakeIOModule.open argument renaming: file_name to file

- pyfakefs/fake_filesystem_unittest.py
When running code on Python 3.7.3, we get this error intermittently: RuntimeError: dictionary changed size during iteration
Creating a list instead of set appears to solve this issue.
> Use snapshot of modules to avoid RuntimeError

- .travis/docker_tests.sh
- Dockerfile
- pyfakefs/tests/fake_os_test.py
- still defaults to master if docker is build without arguments
Just testing if it works with PR - which it does not... gets the wrong repo user name. 
Ok, fixed.
> Use the current pyfakefs branch in docker file

- pyfakefs/fake_scandir.py
- pyfakefs/tests/fake_os_test.py
The documentation for os.DirEntry.path [1] says that the path attribute
of a DirEntry object is only absolute if scandir()'s path argument was
absolute, and simply the name attribute if scandir()'s path argument was
a filedescriptor. This patch makes pyfakefs do this, and adjusts the
tests.
Relative symlinks are now also covered in the scandir tests.
RealScandirFdTest.test_path_like was failing for me in Python 3.7.3 on
Debian Bullseye.
[1] https://docs.python.org/3/library/os.html#os.DirEntry.path
> Fix scandir DirEntry.path for relative path or fd

- CHANGES.md
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/tests/dynamic_patch_test.py
- these module can still hold references to fake modules
- modules already loaded at test start are not affected
- see #501 and #427
> Unload all modules loaded during the test

- docs/usage.rst
Should give pytest users a way to load test resources that does fit with
the style that pytest is normally used.
> Add note about accessing real files in pytest

- CHANGES.md
- docs/usage.rst
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- pyfakefs/tests/import_as_example.py
- works for module-level functions and methods in module-level classes
- this also makes it unnecessary to reload the "tempfile" module
> Added automatic patching of file system functions in default argument

- CHANGES.md
- docs/modules.rst
- docs/usage.rst
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- decorator patchfs is called without arguments (and no parentheses)
- decorator custom_patchfs is called with Patcher arguments
@jmcgeheeiv - please have a look to check if that would be ok!
> Added convenience decorators to patch single functions

- pyfakefs/tests/patched_packages_test.py
test_write_excel fails if pandas are installed but openpyxl is not.
Adjust the condition around the case appropriately.
> Skip test_write_excel if openpyxl is not installed

- pyfakefs/fake_filesystem_unittest.py
`tearDownPyfakefs` is a no-op legacy API, it was given @DeprecationWarning as a decorator... which broke it rather than making it a no-op callable as that isn't a decorator.
This fixes:
```
self.tearDownPyfakefs()
TypeError: 'DeprecationWarning' object is not callable
```
in code updating to a modern pyfakefs that still calls it.
> Remove @DeprecationWarning as it isn't a decorator

- .github/workflows/pythonpackage.yml
- CHANGES.md
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_pathlib.py
- pyfakefs/helpers.py
- pyfakefs/tests/fake_pathlib_test.py
Hello!
Sorry for the PR outa the blue w/out an issue to discuss -- had some time and figured I'd take a crack at it. I added 3.10 beta1 to my ci for some projects using pyfakefs and my builds are failing. Did a bit of sleuthing and it seems there were a few changes to Pathlib for this release. The main issue/thread seems to be [here](https://github.com/python/cpython/pull/19342) -- and associated [commit](https://github.com/python/cpython/commit/2219187cab6bca009c42b63b2f4c30b5b10c916d). This [commit](https://github.com/python/cpython/commit/abf964942f97f6489360a75fd57b5e4f41c75f57) also appears to be related.
I *think* (hope?!) that this fix is backwards compatible. Tests in the docker container all seem happy, and I've tested this locally on my Mac w/ 3.10 beta1 and the tests that …
> fix breaking pathlib change in 3.10 beta1

- CHANGES.md
- README.md
- docs/intro.rst
- docs/usage.rst
- setup.py
- Python 3.5 had EOL 09/2020, and had already been removed from CI tests
- Python 3.5 does not fully support typing
- some minor usage documentation fixes
> Remove support for Python 3.5

- .github/workflows/pythonpackage.yml
- CHANGES.md
- see #608
This runs under Windows and Ubuntu, one Python version only, to avoid adding test dependencies in the future.
Also runs all tests using pytest as an added bonus.
> Add step to find test dependencies

- CHANGES.md
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_scandir.py
- pyfakefs/helpers.py
- pyfakefs/tests/fake_filesystem_test.py
- pyfakefs/tests/fake_pathlib_test.py
This is work in progress, trying to annotate the pyfakefs methods. 
This hopefully helps to find some inconsistencies (already found some in `str` / `byte` handling), but it will take a while.
@AustinScola - if you want to take a look, there are certainly things that can be improved, as I don't have much experience with typing.
> Add type annotations to some fakefs functions

- setup.py
pyfakefs 4.5 removed support for Python 3.5, but the python_requires metadata was not updated to reflect this, which means that pyfakefs can be installed in a Python 3.5 environment but will not run correctly.
> Require Python >= 3.6

- CHANGES.md
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- pyfakefs/tests/fixtures/deprecated_property.py
- also fix a few resource warnings in unit tests
- fixes #614
> Deprecate all warnings while inspecting loaded modules

- extra_requirements.txt
- pyfakefs/tests/fake_os_test.py
- make sure the tested invalid file descriptors are out of valid range
(tests failed in a specific build where the have been to be existing)
> Update pandas to version 1.3.1 for Python > 3.6

- CHANGES.md
- pyfakefs/fake_filesystem.py
- pyfakefs/tests/example.py
- pyfakefs/tests/example_test.py
- pyfakefs/tests/fake_filesystem_glob_test.py
- pyfakefs/tests/fake_filesystem_test.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- affects os.path.split, os.path.splitdrive and glob.glob
- fixes #632
> Fixed handling of alternative path separator in some functions

- docs/usage.rst
I was reading through the usage doc and noticed it referencing a 'is windows_fs' which looks like it is missing an underscore according to the [code](https://github.com/jmcgeheeiv/pyfakefs/blob/e06472b0671d2f077cc41e9ab9cf38893ef0c97f/pyfakefs/fake_filesystem.py#L929).
> Change 'is windows_fs' to 'is_windows_fs'

- CHANGES.md
- pyfakefs/fake_filesystem.py
- makes the output order for os.listdir, `os.scandir` and `pathlib.Path.listdir` random
- see #638
> Randomize list order for FakeFilesystem.listdir

- CHANGES.md
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_filesystem_unittest.py
- all fcntl functions are implemented empty
- see #645
> Add basic patching of fcntl module

- CHANGES.md
- pyfakefs/fake_filesystem.py
- pyfakefs/tests/fake_filesystem_test.py
- pyfakefs/tests/fake_os_test.py
- pyfakefs/tests/test_utils.py
- caused file system file to be wrong for non-empty files
- tests: add contextmanager version of assert_raises_os_error
- fixes #660
Correctly handle reading/writing pipes via file
- make numBytes argument optional
- open real pipe as file and store it if needed
- fixes #661
> Do not set size to 0 on setting initial content

- CHANGES.md
- pyfakefs/fake_filesystem.py
- pyfakefs/tests/fake_filesystem_vs_real_test.py
On open() binary mode should not allow an `encoding` argument. See #664.
If encoding is passed with binary mode, raise: `ValueError(binary mode doesn't take an encoding argument)`
Add unit test helper to check the open() constructor call. Test for both binary and text mode with encoding, where binary fails and text passes.
> Open binary no encoding

- CHANGES.md
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/fake_pathlib.py
- pyfakefs/pytest_plugin.py
- pyfakefs/tests/fake_filesystem_test.py
- avoids the use of FakePathLibPath in pathlib
- add _pytest.pathlib to skipped modules,
fake isinstance check for RealPathlibPathModule
- prevents issue with _pytest.pathlib in pytest 7.0.0,
which would cause all tests with fs fixture to fail
- see #666
> Use RealPathlibModule for all skipped modules

- README.md
- docs/intro.rst
`README.md` and `intro.rst` both had a reference to pytest as "PyTest".  
pytest.org only refers to pytest in all lowercase, and the core team prefers that spelling. 
Also, thanks for including a pytest fixture in pyfakefs. Super cool.
> PyTest -> pytest

- tox.ini
Tested changes with `tox -e py39,py310' and tests pass.
> add Python 3.9 and 3.10 to tox.ini

- CHANGES.md
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_pathlib.py
- pyfakefs/tests/fake_filesystem_test.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- pyfakefs/tests/fake_filesystem_vs_real_test.py
- pyfakefs/tests/fake_os_test.py
- pyfakefs/tests/fake_tempfile_test.py
- as Windows has no root dir as such, we use the
current drive as root dir to better emulate the fs
- as in the real fs, if a path starts with a path separator,
it points to the current drive (e.g. the root of cwd)
- fixes #673
> Change handling of root dir under Windows

- CHANGES.md
- docs/usage.rst
- pyfakefs/fake_pathlib.py
- pyfakefs/pytest_plugin.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- fixes #666 without the need to skip _pytest.pathlib patching
- add module and session scoped fs fixtures
- fixes #684
> Overwrite instance check for PathLibPathModule

- CHANGES.md
- pyfakefs/fake_filesystem.py
- pyfakefs/tests/fake_open_test.py
- the wrong argument had been passed
- fixes #689
> Fix newly introduced support for opener argument in open

- CHANGES.md
- pyfakefs/fake_filesystem.py
- pyfakefs/tests/fake_filesystem_test.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- was always detected as existing
- caused part of #692
> Fix handling of Windows drive as root path

- CHANGES.md
- pyfakefs/fake_filesystem.py
- it may use a cached accessor instead of the fake one
- see #697
> Do not use the build-in opener in pathlib

- .github/workflows/pythonpackage.yml
- .github/workflows/run_pytest.sh
- CHANGES.md
- docs/usage.rst
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/pytest_tests/pytest_module_fixture_test.py
- nested fixtures will reference the outer fixture
This is needed if using module or session scoped fixtures. The current behavior is inconsistent, as it would stop patching after the inner fixture is ended, and break the outer fixture.
If really needed, we may think about adding real nesting behavior, which would be more complicated to implement.
> Do not allow nested fixtures

- CHANGES.md
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/pytest_tests/io.py
- pyfakefs/pytest_tests/pytest_plugin_test.py
- allows using own modules with the same name
- fixes #708
> Do not skip filesystem modules by name

- .github/workflows/pythonpackage.yml
- CHANGES.md
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_scandir.py
- pyfakefs/tests/fake_os_test.py
- pyfakefs/tests/patched_packages_test.py
- the check for the flag was incorrect
- change PyPy version in CI to 3.7
- fixes #723
> Fix handling of O_TMPFILE flag in os.open

- CHANGES.md
- pyfakefs/fake_filesystem.py
- pyfakefs/tests/fake_os_test.py
- pyfakefs/tests/test_utils.py
- rmdir and chmod work without permission if the file user ID is the current user ID
- better handle owner/group/other permission bits
- fixes #719
> Fix handling of read permissions

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE/code_pr.md
- .github/PULL_REQUEST_TEMPLATE/documentation_pr.md
- .github/workflows/release-deploy.yml
- CHANGES.md
- README.md
- docs/intro.rst
- docs/usage.rst
- triggered on publishing a GH release
- includes creation of release documentation
- add PR templates, adapt issue templates
- minor documentation changes
> Add automatic release on PyPI

- .github/workflows/dockertests.yml
- it still uses Python 3.6 per default, which we do not support
> Disable tests for CentOS temporarily

- .github/workflows/dockerfiles/Dockerfile_redhat
- .github/workflows/dockertests.yml
- .github/workflows/testsuite.yml
- CHANGES.md
CentOS is no longer maintained (used to be a free mirror of RH), meanwhile RedHat has published its own public docker image with a subset of the commercial image, so we use that image for tests under RH.
> Replace EOL CentOS with RedHat UBI9 docker image

- .github/workflows/dockertests.yml
- .github/workflows/release-deploy.yml
- .github/workflows/testsuite.yml
The current CI logs some warnings as annotations: `Resolve warning regarding 'Node.js 12 actions are deprecated.'`:
Upgrading to the latest major version solves that.
PS: Dependabot can send automatic updates for [GitHub actions](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem), I can set that up as part of this pull request, if you're interested.
> Update official GitHub actions to the latest major

- .github/workflows/testsuite.yml
- CHANGES.md
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_pathlib.py
- pyfakefs/fake_scandir.py
- pyfakefs/tests/fake_pathlib_test.py
I know this is quite early 😄 but I was trying to test one of my packages to see if it worked and noticed that pyfakefs was returning some errors. I fixed a few issues to make it work on my machine (macOS) but it looks like it now fails due to pandas not installing yet. Also Windows fails but I don't have such a machine, so I might not be the best person to fix these...
Let me know how I should proceed with this. I understand if you want to close or leave this pull request open until all the jobs pass. I'm also happy to split the fixes and leave the CI updates out for now.
However, I do think that having basic support in this package might help others packages to add Python 3.12 compatibility.
> Add Python 3.12 to the test suite

- .github/workflows/dockerfiles/Dockerfile_debian
- .github/workflows/dockerfiles/Dockerfile_fedora
- .github/workflows/dockerfiles/Dockerfile_redhat
- .github/workflows/dockerfiles/Dockerfile_ubuntu
- .github/workflows/dockertests.yml
- CHANGES.md
I noticed that the dockertests [were failing](https://github.com/browniebroke/pyfakefs/actions/runs/3766893340/jobs/6403878811#step:3:977) on my branches. 
I thought it was because they are on a fork, but it's actually because my branches contained slashes `/` which means the [`$(basename $GITHUB_REF)`](https://github.com/pytest-dev/pyfakefs/blob/c617fceb91bf5e4331752fcabb9c1620859b3222/.github/workflows/dockertests.yml#L17) didn't resolve correctly to the branch name. GitHub provides another env variable `GITHUB_REF_NAME` which contains the correct value, so we can just use that instead. 
Fixing this [broke the `unzip` commands](https://github.com/browniebroke/pyfakefs/actions/runs/3766946009/jobs/6403987731#step:3:989) in the Dockerfiles, which we can avoid by setting the filename with …
> Fix dockertests on branches containing slashes

- CHANGES.md
- docs/usage.rst
- pyfakefs/fake_filesystem.py
- pyfakefs/tests/fake_os_test.py
- pyfakefs/tests/fake_pathlib_test.py
- makes it possible to simulate inaccessible paths under Windows
- see #720
> Add "force_unix_mode" flag to FakeFilesystem.chmod

- CHANGES.md
- docs/troubleshooting.rst
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- always exists to conform to the POSIX standard in the real fs
- do not add the used space for the link for test convenience
- see #790
> Create /tmp symlink to temp dir under macOS

- CHANGES.md
- pyfakefs/patched_packages.py
TextFileReader currently overwrites the engine as python when patching for pandas. I am not sure why is it needed since the default engine is "c" and "python" engine doesn't expects certain params like "float_precision" which results in it failing with the version of pandas that we have (1.1.5).
> remove engine overwrite in pandas TextFileReader patch

- .github/workflows/testsuite.yml
- CHANGES.md
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/fake_path.py
- pyfakefs/fake_pathlib.py
- pyfakefs/tests/fake_filesystem_test.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- pyfakefs/tests/fake_os_test.py
- pyfakefs/tests/fake_pathlib_test.py
- pyfakefs/tests/import_as_example.py
- pyfakefs/tests/test_utils.py
- adapt for changed pathlib implementation (removed flavour implementation)
- Windows: add patching for some os.path functions now implemented in nt instead of ntpath
- fix handling of devnull for changed OS
- add fake implementation for os.path.splitroot
- fixes #770
> Add support for current Python 3.12

- CHANGES.md
- pyfakefs/fake_os.py
- pyfakefs/fake_pathlib.py
- pyfakefs/tests/fake_filesystem_shutil_test.py
- pyfakefs/tests/fake_os_test.py
- pyfakefs/tests/fake_pathlib_test.py
- return the faked functions instead of the real ones
- fixes #799
The problem was that until now, the `os.supports_..` properties have been taken from the real `os` in `pyfakefs` itself. This does not work if called by someone in the faked os who checks for a contained function, as it would have found the original instead of the faked function.
> Set the os.supports_xxx properties for the fake filesystem

- CHANGES.md
- docs/troubleshooting.rst
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- TMPDIR may point elsewhere
- fixes #810
> Make sure a /tmp path exists under linux

- CHANGES.md
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/pytest_tests/pytest_plugin_test.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- the temp dir is now created during filesystem initialization instead of at patcher setup
- fixes #814
This slightly changes the behavior if you are creating a fake filesystem without using any of the recommended methods (e.g. the temp directory is now also created in this case), but I think that this is ok.
> Re-create the temp directory on resetting the filesystem

- .github/workflows/testsuite.yml
Make sure pytest tests also work under macOS, see #814.
> Add macOS pytest tests in CI

- tox.ini
```
[jelle@⬢ python311][~/projects/pyfakefs]%HOME=1 USERPROFILE=2 tox -e py311
py311: failed with pass_env values cannot contain whitespace, use comma to have multiple values in a single line, invalid values found 'HOME USERPROFILE'
py311: FAIL code 1 (0.00 seconds)
evaluation failed :( (0.03 seconds)
```
See: https://github.com/tox-dev/tox/issues/2658
> tox.ini: passenv should be comma-separated, not space-separated

- .github/workflows/testsuite.yml
- CHANGES.md
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/fake_pathlib.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- distutils has been removed
- variable renamed in pathlib
- add workaround for patching open, comment out not working tests
- fixes #830 and #831
I will write a separate issue for the remaining problem.
> Adapt to changes in Python 3.12 beta1

- CHANGES.md
- pyfakefs/fake_filesystem_shutil.py
- patch away a Windows-specific optimization in shutil.copy2 to avoid calling the Windows API
- fixes #841
> Adapt fake shutil to changes in Python 3.12 beta2

- docs/usage.rst
- pyfakefs/pytest_tests/pytest_module_fixture_test.py
- avoids linter warning about unused argument
- closes #834
> Use pytest.mark.usefixtures in code snippet

- .github/workflows/dockerfiles/Dockerfile_debian
- .github/workflows/dockerfiles/Dockerfile_ubuntu
- avoids clashes with system-wide packages
- done in debian and ubuntu containers
Currently tests in the Debian container fail for that reason.
> Use virtual environment in docker containers

- pyfakefs/py.typed
- setup.cfg
Adds the `py.typed` file as per PEP 561. This ensures that projects that import pyfakefs can be type checked.
Note: First time working with setuptool so please make sure my change to `setup.cfg` is correct.
> Add py.typed marker file (as defined by PEP 561)

- .pre-commit-config.yaml
- CHANGES.md
- docs/troubleshooting.rst
- pyfakefs/extra_packages.py
- pyfakefs/fake_file.py
- pyfakefs/tests/fake_filesystem_vs_real_test.py
- pyfakefs/tests/fake_open_test.py
- pyfakefs/tests/fake_os_test.py
- found via `codespell -L wronly,afile`
- add `codespell` hook to pre-commit
- ~~fix RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.10'~~
> Fix typos and add `codespell` hook to pre-commit

- .github/workflows/testsuite.yml
- CHANGES.md
- README.md
- docs/intro.rst
- extra_requirements.txt
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/tests/fake_filesystem_test.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- pyfakefs/tests/fake_pathlib_test.py
- setup.cfg
- fixes #869
- fix tests if HOME environment is missing
- fixes #870
- removed support for Python 3.7
(is end of life, and behaves a bit differently so that some of the HOME-related tests failed)
> Remove debug output accidentally left in

- docs/modules.rst
- docs/troubleshooting.rst
- docs/usage.rst
- pyfakefs/fake_filesystem.py
Also mention the return value of create_xxx methods more prominently.
Came up in #872
Added a note about global `pathlib.Path` objects to the troubleshooting section after the review discussion.
> Add some API links to the usage documentation

- docs/troubleshooting.rst
Just simplifying and making the troubleshooting snippet more intuitive.
Follow on to https://github.com/pytest-dev/pyfakefs/pull/873 for https://github.com/pytest-dev/pyfakefs/issues/872.
> Simplifying `pathlib.Path` troubleshooting snippet

- docs/troubleshooting.rst
- Noticed syntax highlighting needed an update
- Single backtick means italics, double backtick means code syntax
- Fixed wording from "type" to "attributes"
- Realized to make the point in the code snippet about `Path`, don't need `create_file` at all
For https://github.com/pytest-dev/pyfakefs/issues/872
> Removed extra create_file from troubleshooting snippet

- docs/usage.rst
- this note is now obsolete
- closes #876
> Remove note about potential change of "patch_open_code"

- .github/workflows/testsuite.yml
- CHANGES.md
- README.md
- docs/intro.rst
- pyfakefs/tests/fake_filesystem_test.py
- pyfakefs/tests/fake_pathlib_test.py
- setup.cfg
- too early to drop it
- disable failing tests for Python 3.7 (expanduser() and home() behave slightly different in 3.7)
I'm not sure what the problem is, it may also have to do with the CI environment (`runneradmin` is returned instead of the configured user - maybe the environment is overwritten). This only happens with Windows and Python 3.7.
> Add back support for Python 3.7

- .github/workflows/dockertests.yml
- .github/workflows/release-deploy.yml
- .github/workflows/testsuite.yml
- docs/modules.rst
- docs/usage.rst
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/fake_os.py
- pyfakefs/fake_path.py
- pyfakefs/fake_pathlib.py
- pyfakefs/pytest_tests/pytest_fixture_param_test.py
- pyfakefs/pytest_tests/pytest_fixture_test.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- pyfakefs/tests/fake_os_test.py
- pyfakefs/tests/fake_pathlib_test.py
- if used with pytest, pytest >= 6.2 is needed (see #885)
- also remove obsolete Python 3.6 references
> Add a note about setUpClassPyfakefs usage

- CHANGES.md
- pyfakefs/fake_filesystem.py
- pyfakefs/tests/fake_pathlib_test.py
- automount drive or UNC path under Windows if needed in FakeFilesystem.makedir() (used by Path.mkdir)
- fixes #890
> Fix pathlib.Path.mkdir() with unmounted path

- CHANGES.md
- pyfakefs/fake_path.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- fixes Windows problem if called from fspath, if the real current drive is not C:
- fixes test for #892 under Windows
Turns out that the fix for #892 actually worked, but with the concrete test code it failed under Windows in the CI because the current working dir was on another drive than C:. 
The notation with a slash (or backslash) at the beginning of the path under Windows means that it uses the current drive. On creating the path, the current drive in the fake fs was used (which is C: by default) by calling `getcwd` in the fake fs, but `importlib.util.spec_from_file_location` used `os.fspath` that under Windows uses `nt.getcwd` instead of `os.getcwd`, which was not patched.
Patching `nt.getcwd` fixes this.
> Add patching getcwd/getcwdb for nt

- CHANGES.md
- docs/usage.rst
- pyfakefs/fake_filesystem.py
- pyfakefs/tests/fake_filesystem_test.py
- changed behavior of add_real_directory() to be able to map a real directory to an existing directory in the fake filesystem
- fixes #901
> Allow merging real with fake directories

- CHANGES.md
- pyfakefs/mox3_stubout.py
Change the `setattr` and `getattr` calls in `pyfakefs/mox3_stubout.py` to directly access the objects `__dict__` attribute. I did this because I was having trouble using pyfakefs in a large codebase that also used PyTorch – which I tracked down to custom `__setattr__` methods [found here](https://github.com/pytorch/pytorch/blob/7bcf7da3a268b435777fe87c7794c382f444e86d/torch/_dynamo/config_utils.py#L68-L74) (among other places).
I saw the comment in `pyfakefs/mox3_stubout.py` mentioning that a switch to manipulating the `__dict__` attribute directly had been considered, and that it would even resolve the special case with static methods losing their `staticmethod` wrapper when accessing them with `getattr`, so I went ahead and made that change throughout the file.
I'm not sure if this will …
> Replace setattr and getattr calls with __dict__ manipulations

- .github/workflows/testsuite.yml
- CHANGES.md
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/fake_io.py
- in Python 3.12, _io is not a simple alias for io
- fixes #910
I have run this without the fix in place, and the Python 3.12 tests failed on all platforms.
> Use a separate fake module for _io

- CHANGES.md
- pyfakefs/fake_filesystem.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- the tempfile module will access the temp path using Windows separators under Windows, even if emulating Posix - this had to be handled
- fixes #912
> Fix separator mismatch with Linux emulated under Windows

- CHANGES.md
- pyfakefs/fake_scandir.py
- pyfakefs/tests/fake_pathlib_test.py
- used to return a Path object for the top dir instead of a string
- fixes #915
> Fix result of os.walk with a path-like top directory

- docs/troubleshooting.rst
- see #926
The timezone case was already mentioned in the troubleshooting guide, just added the code example
> Add example for handling pytz timezones

- CHANGES.md
- pyfakefs/fake_filesystem_unittest.py
- modules loaded dynamically are now reloaded instead of deleted; deleting them caused some unexpected behavior in django
- if reloading failed delete the module as last ressort 
fixes #932
> Reload modules loaded dynamically during test

- CHANGES.md
- docs/usage.rst
- pyfakefs/fake_filesystem_unittest.py
- can be used for cases where dynamic patching causes problems
- see #932
> Add back argument use_dynamic_patch

- CHANGES.md
- docs/usage.rst
- pyfakefs/fake_filesystem_unittest.py
- fixes a regression due to the changed behavior of the dynamic patcher cleanup The modules are now reloaded only if the django module is loaded, or the reload mode set to RELOAD.
- fixes #939
> Introduce and use new argument "module_cleanup_mode"

- CHANGES.md
- docs/usage.rst
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/patched_packages.py
- reload only the django view modules instead of all modules
- change the module cleanup mode default to always delete modules (avoiding problems with reloading other modules)
- should be a better fix for #932
> Use cleanup hook to reload django views

- .github/workflows/testsuite.yml
- CHANGES.md
- pyfakefs/fake_file.py
- pyfakefs/helpers.py
- pyfakefs/tests/fake_open_test.py
- from Python 3.11 on, this is the preferred version
- fixes #957
> Use locale.getencoding instead of getpreferredencoding

- CHANGES.md
- pyfakefs/fake_file.py
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_open.py
- pyfakefs/fake_os.py
- pyfakefs/fake_scandir.py
- pyfakefs/tests/fake_os_test.py
- pyfakefs/tests/fake_pathlib_test.py
- pyfakefs/tests/test_utils.py
- always consider the current user group while evaluating file permissions for user/group/other classes
- fixes #959 and #960
> Correctly handle file permissions for different classes

- CHANGES.md
- docs/troubleshooting.rst
- pyfakefs/fake_file.py
- pyfakefs/fake_filesystem.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
We cannot use the `tempdir` module to get the temp directory at that point, if the root dir is not writable by all. This is a consequence of the fixes fo file permission handling.
Had to add a hack for the case of Windows emulated on macOS and PyPy/Linux (e.g. POSIX systems not supporting O_TMPFILE).
Fixes #965
> Make sure the temp directory can be created during fs reset

- CHANGES.md
- pyfakefs/fake_os.py
- pyfakefs/tests/fake_os_test.py
- also removed check for supported dirfd where not used
- changed dirfd tests to run both in the fake and real OS
- fixed #968
> Fix incorrect handling of dirfd in os.symlink

- CHANGES.md
- pyfakefs/fake_os.py
- pyfakefs/tests/fake_os_test.py
- flags are considered in os.open if present
- closes #972, closes #974
> Add support for O_DIRECTORY and O_NOFOLLOW flags

- CHANGES.md
- README.md
- docs/usage.rst
- pyfakefs/fake_os.py
- pyfakefs/tests/fake_os_test.py
- no tests for real OS (extended atributes not enabled in CI)
- fixes #971
> Fix handling of missing attribute in os.getxattr

- CHANGES.md
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/tests/fake_filesystem_shutil_test.py
- the fd functions that are used for rmtree are not available under Windows -> switched of the usage of these function in the fake fs
- fixes #979
> Fix problem with shutil.rmtree if emulating Windows under POSIX

- CHANGES.md
- pyfakefs/fake_file.py
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_open.py
- pyfakefs/fake_os.py
- pyfakefs/helpers.py
- pyfakefs/tests/fake_open_test.py
- pyfakefs/tests/fake_os_test.py
- fixes #967
This fixes at least some of the issues with permission handling if opening files via the file descriptor.
I'm sure there are more problems, as the description of the behavior in the Python documentation is not sufficient and you have to fall back to OS-specific documentation. Also, there are differences in the behavior between CPython and PyPy.
> Fix permission handling for opening file via file descriptor

- CHANGES.md
- pyfakefs/fake_os.py
- pyfakefs/tests/fake_os_test.py
- use a similar implementation as the real fs
- fixes #987
> Fix behavior of fake os.makedirs

- pyfakefs/fake_pathlib.py
- pyfakefs/tests/dynamic_patch_test.py
- pyfakefs/tests/example.py
- pyfakefs/tests/fake_filesystem_shutil_test.py
- pyfakefs/tests/fake_filesystem_test.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- pyfakefs/tests/fake_filesystem_vs_real_test.py
- pyfakefs/tests/fake_open_test.py
- pyfakefs/tests/fake_os_test.py
- pyfakefs/tests/fake_pathlib_test.py
- pyfakefs/tests/fake_stat_time_test.py
- pyfakefs/tests/fake_tempfile_test.py
- pyfakefs/tests/import_as_example.py
- pyfakefs/tests/test_utils.py
- we have switched the warnings on, so we try to avoid them as much as possible in our own tests
- use utf8 encoding in all tests with no explicit encoding
Related to #957.
> Avoid EncodingWarning occurring in tests

- CHANGES.md
- pyfakefs/fake_open.py
- pyfakefs/tests/fake_os_test.py
- the check had been incorrecty introduced to fix an issue ultimately related to reference counting/garbage collection
- the fix was incorrect, and that case can probably be ignored, as the code laeding to it makes no sense
- fixes #997
> Remove unneeded check leading to a regression

- tox.ini
This change aligns the Python versions that are tested by tox with those tested by CI. In particular:
* py312 is added
* pypy versions are explicitly called out (excluding pypy38, which appears to segfault locally and doesn't seem to be tested in CI)
I attempted to run the tox environments in parallel (using `tox p` or `tox run-parallel`) and discovered that files and symlinks are written to the local directory, causing failures in the parallel test suites due to filesystem access conflicts. This PR doesn't address that issue, which likely requires establishing temp directories at test startup.
> Align Python version testing in tox with CI

- pyfakefs/tests/fake_filesystem_test.py
This PR improves the isolation of filesystem interactions when the test suite is executing. Its purpose is to allow multiple Python interpreters to execute the test suite in parallel (`tox run-parallel`).
* Unique temporary directories are now used for symlink tests.
(Previous behavior was to use the `pytest/tests/fixtures/` directory.)
* Using a unique temporary directory when calling `create_real_paths()`.
(Previous behavior was to append "root" to the end of the OS temp directory path.)
Fixes #1009
> Isolate test suite execution

- CHANGES.md
- pyfakefs/fake_pathlib.py
- pyfakefs/tests/fake_pathlib_test.py
This PR fixes path separators for Windows paths.
> [!NOTE]
>
> A single regression test for #558 fails as a result of this change, and only on Python 3.12. I am uneasy touching this test because I harbor concerns that this test is enforcing behavior that might not be worthwhile to support.
>
> Please review this work, together with this test, and let me know how to proceed. My gut is to remove the failing regression test but I didn't include that here.
Fixes #1006
> Fix pure windows path behavior

- CHANGES.md
- pyfakefs/fake_io.py
- pyfakefs/fake_open.py
- pyfakefs/fake_pathlib.py
- pyfakefs/tests/fake_open_test.py
- pyfakefs/tests/fake_pathlib_test.py
- pyfakefs/tests/skip_open.py
- if a module is skipped using additional_skip_names, Path.open is now handled the same way as io.open to use real fs calls
- fixes #1012
I'm not too happy about the skip module handling, may revisit this later.
> Handle skipped pathlib.Path.open calls

- .github/workflows/testsuite.yml
Still have been using deprecated `set-output`.
> Fix CI warning for deprecated methods

- CHANGES.md
- pyfakefs/fake_file.py
- pyfakefs/fake_pathlib.py
- pyfakefs/tests/fake_open_test.py
- pyfakefs/tests/fake_pathlib_test.py
- pyfakefs/tests/skipped_pathlib.py
> Handle other pathlib.Path.open calls in read_text, read_bytes, write_text and write_bytes

- .github/workflows/testsuite.yml
- CHANGES.md
- legacy_requirements.txt
- pyfakefs/fake_file.py
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/fake_open.py
- pyfakefs/fake_path.py
- pyfakefs/fake_pathlib.py
- pyfakefs/helpers.py
- pyfakefs/pytest_tests/pytest_reload_pandas_test.py
- pyfakefs/tests/fake_filesystem_glob_test.py
- pyfakefs/tests/fake_filesystem_test.py
- pyfakefs/tests/fake_os_test.py
- pyfakefs/tests/fake_pathlib_test.py
- pyfakefs/tests/test_utils.py
- account for changes in pathlib implementation
- reload glob to account for changed implementation
- improve handling of admin user under Windows
- add os.isreserved
- change os.path.isabs under Windows
- add worksaround for recursion with linecache
- exclude extra dependencies tests for 3.13 under Windows (pandas not available yet)
Fixes #1017.
> Preliminary support for Python 3.13

- .pre-commit-config.yaml
- CHANGES.md
- docs/troubleshooting.rst
- docs/usage.rst
- pyfakefs/fake_file.py
- pyfakefs/fake_open.py
- pyfakefs/tests/example_test.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
This PR introduces the following changes:
* Immunized usage of `io.open()` so it doesn't get rewritten by pyupgrade
* Ran `upadup` to update pre-commit hooks' `additional_dependencies`
* Ran `pre-commit run -a` to fix the docs based on a much newer black version used by blacken-docs
* Added pyupgrade as a pre-commit hook, with Python 3.7+ idioms enforced
Closes #1020
> Use pyupgrade

- CHANGES.md
- pyfakefs/fake_filesystem.py
- pyfakefs/tests/fake_filesystem_test.py
* allows to ignore the umask
* closes #1038
> Add apply_umask argument to FakeFilesystem.create_dir

- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/fake_open.py
- replaces previous workaround that somewhat broke the linecache
- needed because os is now imported locally
> Patch linecache in Python 3.13

- .pre-commit-config.yaml
- CHANGES.md
- pyfakefs/fake_file.py
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/fake_io.py
- pyfakefs/fake_open.py
- pyfakefs/fake_os.py
- pyfakefs/fake_path.py
- pyfakefs/fake_pathlib.py
- pyfakefs/helpers.py
- pyfakefs/tests/fake_pathlib_test.py
- pyfakefs/tests/skipped_pathlib.py
Add a call stack check for fake filesystem, `os` and `os.path` methods in their `handle_original_call` wrapper to see if they are being called from a module listed in `skip_modules`.
> [WIP] Make fake filesystem, fake `os` and fake `os.path` respect `additional_skip_names`

- CHANGES.md
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_os.py
- pyfakefs/tests/fake_os_test.py
- restrict availability for fd argument in os.chmod (not available in Windows for Python < 3.13)
Noticed this while checking the changes in Python 3.13 - we don't support `os.fchmod` so far.
> Add support for os.fchmod

- CHANGES.md
- pyfakefs/fake_scandir.py
- pyfakefs/tests/fake_os_test.py
- fixes #1051
Trivial fix - create iterator from tuple of results.
> Allow removing entries while iterating over scandir results

- CHANGES.md
- pyfakefs/fake_file.py
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_path.py
- pyfakefs/fake_pathlib.py
- pyfakefs/helpers.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- pyfakefs/tests/fake_pathlib_test.py
Adding tests to document subtle pyfakefs differences described in issue 1053
> Fix some problems with pathlib PosixPath/WindowsPath behavior

- CHANGES.md
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/fake_pathlib.py
- pyfakefs/tests/fake_pathlib_test.py
- patch glob instead
- avoids performance hit on tests
> Avoid reloading glob in Python 3.13

- pyfakefs/fake_open.py
- pyfakefs/helpers.py
Slightly improves the setup times (seen in performance tests).
> Optimization: only analyze traceback if needed

- CHANGES.md
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_pathlib.py
- pyfakefs/tests/fake_pathlib_test.py
Adds tests specific to PurePosixPath and PureWindowsPath to catch issues like #1065
> Add specific tests for PurePosixPath and PureWindowsPath

- CHANGES.md
- pyfakefs/fake_io.py
- pyfakefs/pytest_tests/fake_fcntl_test.py
- had been removed accidentally in 5.7.0
- fixes #1074
While adding support for skipped modules, the forwarding of unfaked attributes to the real fcntl module had been removed accidentally.
> Forward unfaked fcntl calls to real module

- CHANGES.md
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- pyfakefs/tests/performance_test.py
- patch tempfile instead directly (Posix only)
Reload takes between 0.5 and 1 ms, which is a substantial part of the test setup, as no caching can be done here.
This made the setup under Posix slower than under Windows.
> Performance: do not reload tempfile

- CHANGES.md
- docs/usage.rst
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- works only if open_code patch mode is not off
- see #1079
This will not handle all possible cases. Relative imports are not supported, and for absolute imports in dot notation an `__init__.py` is expected in module paths above the leaf module.
> Add some support for loading fake modules

- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- was missing in previous commit
> Fix loading of fake modules for relative imports

- CHANGES.md
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- added Patcher.RUNTIME_SKIPMODULES to allow to skip modules whose name starts with specific strings, if the related debuuger is loaded
- only done for debugger used in PyCharm and VSCode
I have not added any documentation, as this is still experimental. We have to see if this is sufficient to fix the problems with the debugger (see #1083), or if more is needed.
> Add checks to avoid patching debugger modules

- .github/workflows/testsuite.yml
- CHANGES.md
- pyfakefs/pytest_plugin.py
- add more hooks to ensure pause/resume for module and session scoped fs fixtures
- fixes #1101
> Make sure that patching is correctly stopped

- .github/workflows/testsuite.yml
- CHANGES.md
- docs/troubleshooting.rst
- pyfakefs/helpers.py
- pyfakefs/pytest_tests/lib_using_pathlib.py
- pyfakefs/pytest_tests/local_import.py
- pyfakefs/pytest_tests/test_reload_local_import.py
- fix and expand the documentation for cleanup handlers
- add a convenience handler for module reload and a respective test
This came up in connection with #1105, where such a handler can resolve the problem.
> Fix cleanup handler documentation

- .github/workflows/testsuite.yml
- CHANGES.md
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/fake_pathlib.py
- pyfakefs/tests/fake_pathlib_test.py
- work around new class checks in pathlib
There are more checks in `pathlib` using `is` (`is posixpath`), which cannot be faked, so this has to be worked around...
This is 3.14-alpha4, I expect more changes to come. The tests with extra packages are disabled for 3.14, because not all packages are available yet, as expected.
> Add CI tests for Python 3.14 pre-release

- .github/workflows/testsuite.yml
- CHANGES.md
- pyfakefs/fake_file.py
- pyfakefs/tests/fake_open_test.py
- caused missing content if writing over the buffer end
- fixes #1120
- temporarily disable Python 3.14 in CI (current alpha 5 fails some tests)
> Fix content update after flush

- .github/workflows/testsuite.yml
- pyfakefs/fake_filesystem_unittest.py
- do not patch globber.scandir in 3.14
- switch off copy file range optimization (Linux only)
> Adapt to Python 3.14 alpha 5

- CHANGES.md
- pyfakefs/fake_filesystem_unittest.py
- patching it for Python 3.12 under Posix could break pytest tests under some conditions
- should fix #1126
> Only patch linecache in 3.12 for Windows

- CHANGES.md
- pyfakefs/fake_os.py
- pyfakefs/tests/fake_filesystem_shutil_test.py
- pyfakefs/tests/fake_filesystem_test.py
- pyfakefs/tests/fake_filesystem_vs_real_test.py
- pyfakefs/tests/fake_open_test.py
- pyfakefs/tests/fake_os_test.py
- pyfakefs/tests/fake_pathlib_test.py
- pyfakefs/tests/test_utils.py
- found after enabling symlink tests for Windows
> Fix os.access behavior for symlinks under Windows

- CHANGES.md
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_os.py
- pyfakefs/fake_scandir.py
- pyfakefs/tests/fake_filesystem_vs_real_test.py
- pyfakefs/tests/fake_os_test.py
- restores the behavior before version 5.4.0
- fix permission error on reading file type
- fix os.access() behavior for root user
- fix os.scandir(None) behavior
- see #1122
I had first tried to add more tests to `FakeFilesystemVsRealTest`, but have decided to leave that for later as it got a bit out of hand.
This is a minimal fix for the observed problems, and a reversal in the behavior of `FakeFilesystem.get_object()` so that it can be used as before independent of permissions.
> Ignore permissions in FakeFilesystem.get_object()

- docs/intro.rst
- docs/troubleshooting.rst
- docs/usage.rst
- also fix some minor documentation issues
- see #1102
> Document problems with multi-threading

- CHANGES.md
- pyfakefs/fake_io.py
- pyfakefs/fake_open.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- happened in Python > 3.11 due to the handling of linecache in connection with a faked open_code call
- fixes #1121
> Fix recursion on dynamic import from fake file

- docs/troubleshooting.rst
> Add troubleshooting chapter for tmp_path caveat

- CHANGES.md
- pyfakefs/tests/fake_open_test.py
- default buffer size has increased from 8 kB to 128 kB
> Adapt test for increased buffer size in Python 3.14

- docs/troubleshooting.rst
> Rework chapter about fixtures working in the filesystem

- CHANGES.md
- pyfakefs/fake_filesystem_unittest.py
- ignore the pytest executable capitalization
- fixes #1096 (again)
> Make workaround for a recursion more robust

- CHANGES.md
- docs/convenience.rst
- docs/modules.rst
- docs/troubleshooting.rst
- pyfakefs/fake_file.py
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/fake_io.py
- pyfakefs/fake_open.py
- pyfakefs/fake_os.py
- pyfakefs/fake_path.py
- pyfakefs/fake_pathlib.py
- pyfakefs/fake_scandir.py
- pyfakefs/helpers.py
- pyfakefs/tests/fake_filesystem_test.py
- adds the metadata of a package to the fake filesystem
- see #1155
> Add convenience function add_package_metadata

- CHANGES.md
- docs/convenience.rst
- docs/intro.rst
- docs/usage.rst
- pyfakefs/fake_file.py
- pyfakefs/fake_filesystem.py
- pyfakefs/fake_os.py
- pyfakefs/tests/fake_filesystem_shutil_test.py
- makes it more consistent with real messages
- documentation: add a few links to the intro
- see #1159
> Remove "in the fake filesystem" from OSError message

- CHANGES.md
- pyfakefs/fake_file.py
- pyfakefs/fake_open.py
- pyfakefs/tests/fake_open_test.py
- conforms to the IO protocol
- fixes #1162
> Add missing `mode` property to fake file wrapper

- CHANGES.md
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/fake_pathlib.py
- pyfakefs/tests/fake_filesystem_test.py
- pyfakefs/tests/fake_pathlib_test.py
- needs a patched os in Python >= 3.11
- fixes #1169 
This may break one rather special test if `pathlib2` is installed, but I'm goin to ignore this - `pathlib2` is depretated and will be removed in pyfakefs 6.
> Fix instantiation of standalone FakePathlibModule

- CHANGES.md
- pyfakefs/fake_path.py
- pyfakefs/tests/fake_filesystem_test.py
- has been introduced in latest patch version of Python >= 3.10
- fixes #1180
> Add support for new strict value "ALLOW_MISSING" in os.path.realpath

- CHANGES.md
- pyfakefs/fake_filesystem_shutil.py
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/fake_pathlib.py
- allows to use FakeShutilModule outside of Patcher
- see #1171
> Move shutil patches to fake shutil module

- CHANGES.md
- pyfakefs/fake_filesystem_shutil.py
- pyfakefs/fake_pathlib.py
- pyfakefs/tests/fake_filesystem_test.py
- remove incorrect documentation about stand-alone usage
- fix patching of global variables
This mainly fixes the latest PR that was quite buggy, and had added incorrect documentation, see #1171 and #1182.
> Add thread lock for global patches

- CHANGES.md
- pyfakefs/fake_path.py
- pyproject.toml
- fixes the handling of `strict` argument in `os.path.realpath` in Python >= 3.9.23
- adds back the tests into the PyPi packages (fixes #1186)
> Fix packaging problems with 5.9.0 release

- CHANGES.md
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/helpers.py
- pyfakefs/tests/fake_filesystem_test.py
- pyfakefs/tests/fake_filesystem_unittest_test.py
- pyfakefs/tests/fake_filesystem_vs_real_test.py
- pyfakefs/tests/fake_open_test.py
- pyfakefs/tests/skipped_pathlib.py
- fix encoding warnings
- fix unclosed tempfile warnings, fixes #1190
> Fix warnings in tests

- CHANGES.md
- docs/usage.rst
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/pytest_plugin.py
- pyfakefs/pytest_tests/test_fs_with_monkeypatch.py
- use hookwrapper to disable patching during reporting
- disable patching between tests for non function-scope fixtures
- fixes #1200
> Fix handling of pausing fs during reporting

- CHANGES.md
- pyfakefs/fake_filesystem.py
- pyfakefs/pytest_tests/pytest_fixture_test.py
- pause patching to get the metadata path
- seems to never have properly worked
- fixes #1205
> Fix fake_filesystem.add_package_metadata

- CHANGES.md
- pyfakefs/fake_filesystem_unittest.py
- pyfakefs/tests/fake_tempfile_test.py
- a Debian patch to tempfile.py broke patching
- fixes #1214
> Fix patching of Debian-specific tempfile
