pytest-dev/pyfakefs

setup.py
(If this was a deliberate anti spam strategy, maybe add a comment)
=> Typo in AUTHOR_EMAIL

fake_filesystem_unittest.py
Fixes https://github.com/jmcgeheeiv/pyfakefs/issues/54
=> Use unittest2 on python < 2.7

fake_filesystem.py, fake_filesystem_unittest_test.py, fake_tempfile.py, fake_tempfile_test.py
Also add a test to make sure the unittest module picks it up.
=> Add TemporaryDirectory to the tempfile module

MANIFEST.in, README.md, example.py, example_test.py, fake_filesystem_glob_test.py, fake_filesystem_shutil_test.py, fake_filesystem_test.py, fake_filesystem_unittest_test.py, fake_filesystem_vs_real_test.py, fake_tempfile_test.py, pyfakefs/fake_filesystem.py, pyfakefs/fake_filesystem_glob.py, pyfakefs/fake_filesystem_shutil.py, pyfakefs/fake_filesystem_unittest.py, pyfakefs/fake_tempfile.py, setup.py
This should enable PyPi usage.
=> Add a pyfakefs/ module directory; include README.md and COPYING files

fake_filesystem_test.py, pyfakefs/fake_filesystem.py
=> Add support for os.fsync() and os.fdatasync() with corresponding tests

fake_filesystem_shutil_test.py, pyfakefs/fake_filesystem_shutil.py
- add support for ignore_errors and onerror arguments for shutil.rmtree
- added tests
- Handles issue #72
=> Add support for rmtree additional args

example.py
I believe this should work on Windows as well as UNIX-based systems, but I have no Windows.  Could I get confirmation?
=> Update example.py doctest to pass on Windows.

fake_filesystem_test.py, pyfakefs/fake_filesystem.py
- activated under Windows/MacOS
- handles issue #69
=> Added support for case-insensitive filesystem

fake_filesystem_test.py
=> Fixed testGetattrForwardToRealOsPath() under Windows

fake_filesystem_test.py, pyfakefs/fake_filesystem.py
- fixed behavior of NormalizePath() and JoinPaths() with drive letters
- shall fix issue #83
=> Fixed support for drive letter

fake_filesystem_shutil_test.py, fake_filesystem_test.py, pyfakefs/fake_filesystem.py, pyfakefs/fake_filesystem_shutil.py
- added parameter to set the total size of the filesystem
- keep track of used size for added and deleted files
- raise IOError for insufficient space on creating or resizing a file
- added shutil.disk_usage() implementation
- see issue #86
=> Adding support for filesystem size

fake_filesystem_test.py, pyfakefs/fake_filesystem.py
=> Fixed behavior of ResolvePath() for Windows paths

fake_filesystem_test.py, pyfakefs/fake_filesystem.py
- several fixes for drive letter support
- initial (very basic) support for UNC paths
=> Drive letter fixes

fake_filesystem_test.py, pyfakefs/fake_filesystem.py
=> Fixed file system size handling during rename

fake_filesystem_test.py, pyfakefs/fake_filesystem.py
- added check for st_nlink in file system size change
- moved raising out of space IOError to single location
- added test, disabled some tests under Windows
=> Fixed handling of file system size with hard links

fake_filesystem_shutil_test.py, fake_filesystem_test.py, pyfakefs/fake_filesystem.py, pyfakefs/fake_filesystem_shutil.py
- added AddMountPoint() together with support for st_ino and st_dev
- adapted GetDiskUsage() and ChangeDiskUsage() to use the file system given by path, added SetDiskUsage() convenience function
- added FakeOsModule.ismount() implementation
- moved rename implementation to FakeFilesystem.RenameObject(), adapted
it and shutil.move() to correctly behave with same and different file systems
- added auto-mount for Windows drives and UNC paths and some related fixes 
- adapted/added tests
Fixes #25
=> Added support for mount points

fake_filesystem_test.py, pyfakefs/fake_filesystem.py
=> Fix problem copying byte contents

pyfakefs/fake_filesystem.py
=> Pass non-faked io module calls to original module

fake_filesystem_test.py, pyfakefs/fake_filesystem.py
- added tests also for case sensitive behavior
- fixed exception type thrown by getsize()
- fixes #112
=> Fixed some problems with case-insensitive file system

example.py, example_test.py, fake_filesystem_test.py, pyfakefs/fake_filesystem.py
=> Added fake os.scandir for Python >= 3.5

README.md, conftest.py, pyfakefs/fake_filesystem.py, pytest_doctest_test.py
We need @megapctr 's comment on #43 before claiming that this PR actually fixes #43 .
=> WIP: Support for PyTest

.travis.yml, CHANGES.md, fake_filesystem_test.py, pyfakefs/fake_filesystem.py, pyfakefs/fake_filesystem_glob.py, pyfakefs/fake_pathlib.py, pyfakefs/fake_tempfile.py
- added support for context manager in scandir iterator (used in pathlib and glob)
- fixed incorrect usage of random generator in fake_tempfile
- added handling for path-like objects for some functions
- added Python 3.6 in Travis CI
=> Python3 6 support

CHANGES.md, example.py, example_test.py, fake_filesystem_glob_test.py, fake_filesystem_test.py, fake_filesystem_unittest_test.py, pyfakefs/fake_filesystem.py, pyfakefs/fake_filesystem_glob.py, pyfakefs/fake_filesystem_shutil.py, pyfakefs/fake_tempfile.py, setup.py
- slightly reworked some docstrings, added missing docstrings 
- changed behavior of listdir() to returns unsorted entries as in the real function
=> Docstring consolidation

pyfakefs/fake_filesystem_unittest.py
- proposed by @mirosval in #135
=> Added context manager for Patcher

CHANGES.md, fake_filesystem_test.py, pyfakefs/fake_filesystem.py
=> Added support for exclusive creation mode in open

fake_filesystem_test.py, pyfakefs/fake_filesystem.py
=> Added FakeDirectory.ordered_dirs

CHANGES.md, fake_filesystem_test.py, pyfakefs/fake_filesystem.py
Merge release 3.0 into master.
=> Version 3.0

.gitignore, tox.ini
=> Fix & update tox support

fake_pathlib_test.py, pyfakefs/fake_pathlib.py
- make it depend on posic vs. windows instead of case sensitivity of
file system
- see #167
=> Change case handling for pathlib

README.md
README.md updates per tox discussion. cc @mrbean-bremen
=> README.md cleanup + unit test & tox info

README.md
=> Add protocol to pytest docs link in readme

.travis.yml, CHANGES.md, README.md, all_tests.py, docs/usage.rst, example_test.py, mox3_stubout_example.py, mox3_stubout_test.py, pyfakefs/fake_filesystem_unittest.py, pyfakefs/mox3_stubout.py, requirements.txt, setup.py, tox.ini
- removed dependency on mox3
- see #182
=> Copied mox3 stubout into pyfakefs

CHANGES.md, fake_filesystem_test.py, pyfakefs/fake_filesystem.py
- added FakeOsModule.getcwdb() for Python 3
- see #187
=> Corrected handling of byte/unicode paths in several functions

fake_filesystem_test.py, pyfakefs/fake_filesystem.py
=> Added support for ns argument in os.utime

CHANGES.md, fake_filesystem_test.py, fake_filesystem_unittest_test.py, fake_pathlib_test.py, pyfakefs/fake_filesystem.py
- added fake stat_result to make this possible
- fixes #196
=> Added xtime_ns in stat result

CHANGES.md, fake_filesystem_test.py, pyfakefs/fake_filesystem.py
=> Added support for fake os.path.samefile

CHANGES.md, fake_filesystem_test.py, pyfakefs/fake_filesystem.py
=> Make sure adding object to a symlinked directory works

CHANGES.md, fake_filesystem_test.py, pyfakefs/fake_filesystem.py
- added for os.utime, os.chmod, os.chdir, os.chown, os.listdir, os.stat and os.lstat
- fixes #205
=> Added possibility to use open file descriptor as path

CHANGES.md, fake_filesystem_test.py, fake_pathlib_test.py, pyfakefs/fake_filesystem.py
=> Added support for dir_fd argument in several os functions

CHANGES.md, fake_filesystem_shutil_test.py, pyfakefs/fake_filesystem.py, pyfakefs/fake_filesystem_shutil.py
- adapted tests to work with fake_filesystem_unittest.TestCase
- fixed some tests
- fake_filesystem.ResolvePath: consider alternative path separator for resolving links
- fixes #194
=> Removed most of FakeShutilModule functionality

.travis.yml, .travis/install.sh, CHANGES.md, dynamic_patch_test.py, example_test.py, fake_filesystem_glob_test.py, fake_filesystem_shutil_test.py, fake_filesystem_test.py, fake_filesystem_unittest_test.py, fake_filesystem_vs_real_test.py, fake_tempfile_test.py, mox3_stubout_test.py, pyfakefs/fake_filesystem_unittest.py, requirements.txt, setup.py, tox.ini
=> Removed Python 2.6 support

README.md, docs/modules.rst, docs/usage.rst, dynamic_patch_test.py, example_test.py, fake_filesystem_glob_test.py, fake_filesystem_shutil_test.py, fake_filesystem_test.py, fake_filesystem_unittest_test.py, fake_filesystem_vs_real_test.py, fake_pathlib_test.py, fake_tempfile_test.py, pyfakefs/deprecator.py, pyfakefs/fake_filesystem.py, pyfakefs/fake_filesystem_shutil.py, pyfakefs/fake_filesystem_unittest.py, pyfakefs/fake_pathlib.py, pyfakefs/pytest_plugin.py, pytest_plugin_test.py
- changed methods names
- added old method names as depracated version
- added possibility to switch on deprecation warning
- see #186
=> Make pyfakefs API PEP-8 compliant

pyfakefs/fake_filesystem.py, pyfakefs/tests/fake_os_test.py
=> Added handling for creating broken symlinks with trailing separator

pyfakefs/fake_filesystem.py, pyfakefs/tests/fake_os_test.py
=> Added more handling for trailing separators in readlink

pyfakefs/fake_filesystem.py, pyfakefs/tests/fake_os_test.py
=> Added handling for rename symlink with trailing sep to self

pyfakefs/fake_filesystem.py, pyfakefs/tests/fake_os_test.py
=> Added handling for opening a link pointing to a path ending with sep

CHANGES.md, pyfakefs/fake_filesystem.py, pyfakefs/tests/fake_pathlib_test.py
- concerns create_file(), create_dir(), create_symlink(), add_real_file() and add_real_directory()
- closes #409
=> Added support for path-like object argument in convenience methods

pyfakefs/fake_filesystem.py, pyfakefs/tests/fake_filesystem_test.py, pyfakefs/tests/fake_os_test.py
=> Handle contents=None in create_file() as empty contents if size not set

pyfakefs/fake_filesystem_unittest.py, pyfakefs/tests/fake_filesystem_unittest_test.py
=> Import zipfile to avoid problem with late import

CHANGES.md, pyfakefs/fake_filesystem.py, pyfakefs/tests/all_tests.py, pyfakefs/tests/fake_open_test.py, pyfakefs/tests/fake_stat_time_test.py, pyfakefs/tests/test_utils.py
- tests originally by @simonfagerholm, adapted
- fixes #435
=> Adapted file timestamp update to real fs behavior

CHANGES.md, pyfakefs/fake_filesystem.py, pyfakefs/tests/fake_filesystem_shutil_test.py, pyfakefs/tests/fake_filesystem_test.py, pyfakefs/tests/fake_open_test.py, pyfakefs/tests/fake_os_test.py
- can be used to test root user
- see #431
=> Added ability to set user ID

CHANGES.md, docs/modules.rst, pyfakefs/fake_filesystem.py, pyfakefs/fake_filesystem_unittest.py, pyfakefs/tests/fake_filesystem_unittest_test.py, pyfakefs/tests/import_as_example.py, pyfakefs/tests/pytest/pytest_plugin_test.py
- can be called from the unit test, the patcher or the fs
- see #448
=> Added support for pause/resume patching of the file system modules

.dockerignore, Dockerfile, README.md
I got my Dockerfile set up with the right locale and with non-root user `pyfakefs`.
The main purpose of this test is an example Dockerfile.  The tests are not actually run in Docker.
=> Execute the tests in a Docker container

.travis.yml, .travis/docker_tests.sh, .travis/install.sh, .travis/run_pytest.sh, .travis/run_tests.sh, pyfakefs/tests/fake_os_test.py
- run for Python 3.6 Linux build only
=> Added running tests in Docker image

.travis/run_tests.sh, CHANGES.md, pyfakefs/fake_filesystem.py, pyfakefs/helpers.py, pyfakefs/tests/fake_filesystem_shutil_test.py, pyfakefs/tests/fake_filesystem_test.py, pyfakefs/tests/fake_open_test.py, pyfakefs/tests/fake_os_test.py
- added tests running as root to test both root and non-root cases
- adapted code and tests to consider root access
=> Set initial user and group IDs to real IDs

CHANGES.md, pyfakefs/extra_packages.py, pyfakefs/fake_filesystem_unittest.py
- use pathlib2 as pathlib if present
- shall fix #467
=> Patch both pathlib and pathlib2 if present

docs/usage.rst
Closes #476. I just kept it short and sweet but just let me know if there's anything you want me to change.
=> document existence of temporary directories

CHANGES.md, pyfakefs/fake_filesystem.py, pyfakefs/tests/fake_open_test.py
=> Add __next__ to FakeFileWrapper

CHANGES.md, setup.py
@jmcgeheeiv - please check the wording!
=> Added note about dropping Python 2 support

.github/workflows/dockertests.yml, .github/workflows/pythonpackage.yml, CHANGES.md, pyfakefs/fake_filesystem.py, pyfakefs/tests/fake_filesystem_test.py
=> Fix handling of byte strings in os.path.exists/isfile/islink/isdir/ismount

CHANGES.md, README.md, pyfakefs/fake_filesystem.py, pyfakefs/fake_pathlib.py, pyfakefs/tests/fake_filesystem_test.py, pyfakefs/tests/fake_os_test.py, pyfakefs/tests/fake_pathlib_test.py, setup.py
- new strict argument for os.path.realpath()
- new follow_symlinks argument for pathlib.Path.chmod()
- new method pathlib.Path.hardlink_to
- new 'newline' argument in pathlib.Path.write_text()
=> Add support for some Python 3.10 changes

pyfakefs/tests/fake_os_test.py, pyfakefs/tests/fake_stat_time_test.py, pyfakefs/tests/test_utils.py
- avoids test dependencies, see #608
=> Make sure mocked time and float time are reset

docs/usage.rst, pyfakefs/pytest_tests/conftest.py, pyfakefs/pytest_tests/pytest_plugin_test.py
- see #609
As proposed by @jmcgeheeiv.
=> Add example for alias for fs fixture

pyfakefs/fake_filesystem.py, pyfakefs/fake_filesystem_unittest.py, pyfakefs/helpers.py, pyfakefs/tests/fake_filesystem_test.py
- includes FakeOsModule, FakePathModule and FakeIoModule
- fix a couple of str/bytes inconsistencies
- see #599
=> Add type hints to more fake classes

pyfakefs/fake_filesystem.py, pyfakefs/helpers.py
- includes FakeFileOpen and all file wrapper classes
- see #599
=> Add type hints for more classes

pyfakefs/fake_filesystem.py, pyfakefs/fake_filesystem_unittest.py
=> Add type hints to fake_filesystem_unittest

CHANGES.md, pyfakefs/tests/fake_open_test.py
=> Skip failing tests on systems with ASCII locale

CHANGES.md, pyfakefs/fake_filesystem.py, pyfakefs/tests/fake_filesystem_shutil_test.py
- rename is implemented via remove/add, a failed add shall revert the remove
- see #643
=> Make sure nothing is changed if a rename failed

CHANGES.md, pyfakefs/fake_filesystem.py, pyfakefs/tests/fake_filesystem_test.py
- do not update flush position before disk size is checked
- see #660
=> Correctly handle full disk after append

CHANGES.md, pyfakefs/fake_filesystem_unittest.py
- have been made in version 3.3.0,
apparently cause hanging tests with torch import
- no performance degradation detected
- see #693
=> Revert some performance optimizations

CHANGES.md, pyfakefs/fake_filesystem.py, pyfakefs/tests/fake_filesystem_shutil_test.py
=> Add support for path-like objects in shutil.disk_usage

README.md, docs/api.rst, docs/intro.rst, docs/usage.rst, pyfakefs/fake_filesystem.py
- remove link to pyfakefs.org
- make pytest more prominent
=> Minor documentation changes

CHANGES.md, pyfakefs/helpers.py, pyfakefs/tests/fake_os_test.py
=> Add some support for st_blocks in stat result

.github/workflows/builddocs.yml, .github/workflows/dockerfiles/Dockerfile_centos, .github/workflows/dockerfiles/Dockerfile_debian, .github/workflows/dockerfiles/Dockerfile_fedora, .github/workflows/dockerfiles/Dockerfile_ubuntu, CHANGES.md, CONTRIBUTING.md, Dockerfile, README.md, docs/intro.rst, docs/troubleshooting.rst, docs/usage.rst, pyfakefs/tests/fake_open_test.py
- also adapt after renaming master to main branch
=> Update documentation after transfer to pytest-dev

README.md, docs/usage.rst
=> Fix broken links in README

CHANGES.md, docs/usage.rst
=> Minor documentation fixes

docs/troubleshooting.rst
As discussed on #170, we expand the troubleshooting section to include some instructions for adding pyfakefs to a django project without breaking existing tests.
=> Update troubleshooting to include django info

.github/ISSUE_TEMPLATE/bug_report.md, README.md, docs/usage.rst
- fix getting version in bug report template
=> Adapt summary in README

.github/workflows/testsuite.yml, CHANGES.md, pyfakefs/__init__.py, pyfakefs/fake_file.py, pyfakefs/fake_filesystem.py, pyfakefs/fake_filesystem_unittest.py, pyfakefs/fake_io.py, pyfakefs/fake_open.py, pyfakefs/fake_os.py, pyfakefs/fake_path.py, pyfakefs/fake_pathlib.py, pyfakefs/helpers.py, pyfakefs/mox3_stubout.py, pyfakefs/patched_packages.py, pyfakefs/tests/test_utils.py
This is just to get some starting point for pytype support.
I fixed very few problems, the rest is just ignore comments to silence the pytype errors.
I also excluded the tests (as we do for mypy), as they have a lot of problems, and at this stage, I'm not really interested in fixing these.
=> Add pytype CI and pytype ignore comments where needed

.github/workflows/testsuite.yml, CHANGES.md, pyfakefs/pytest_plugin.py, pyfakefs/pytest_tests/ns_package/test/ns_package/test/test_file.py
- fixes some specific tests in namespace packages
- fixes #814
=> Exclude pytest modules from patching

CHANGES.md, docs/troubleshooting.rst
=> Add note regarding `sqlite3` incompatibility

.github/workflows/testsuite.yml, CHANGES.md, pyfakefs/fake_io.py, pyfakefs/fake_os.py, pyfakefs/fake_pathlib.py, pyfakefs/pytest_plugin.py, pyfakefs/tests/fake_filesystem_shutil_test.py, pyfakefs/tests/fake_open_test.py, pyfakefs/tests/patched_packages_test.py
- adapt to some changed behavior
- add another SKIPMODULE for pytest
- add tests for more pypy versions
- see #859
=> Adapt to work with pypy 3.10

.readthedocs.yaml
=> Add now required ReadTheDocs config file

.github/workflows/testsuite.yml, CHANGES.md, docs/usage.rst, pyfakefs/fake_filesystem_unittest.py, pyfakefs/pytest_plugin.py, pyfakefs/pytest_tests/segfault_test.py
- avoids problems with cached modules during session shutdown
- see #866
=> Clear fs cache on session finish

.github/workflows/testsuite.yml, CHANGES.md, pyfakefs/fake_filesystem_unittest.py, pyfakefs/pytest_tests/pytest_fixture_test.py
- caused exception while scanning modules
- fixes #923
=> Handle unhashable modules

CHANGES.md, MANIFEST.in
- also add mypy.ini and the requirements files
- see #937
=> Include tox.ini into the source distribution

docs/troubleshooting.rst, docs/usage.rst
- add needed imports
- fix a few incorrect tests
- closes #946
=> Fix some documentation examples

.pre-commit-config.yaml, pyfakefs/fake_filesystem.py, pyfakefs/fake_open.py, pyfakefs/fake_os.py, pyfakefs/fake_path.py, pyfakefs/helpers.py, pyfakefs/patched_packages.py
- adapt formatting where needed
=> Replace black and flake 8 with ruff

CHANGES.md, docs/troubleshooting.rst, docs/usage.rst
This came up in a Stack Overflow question.
=> Add chapter about nested fake filesystems to troubleshouting guide

docs/troubleshooting.rst, docs/usage.rst
- add basic description of the module cleanup hooks
=> Troubleshooting guide: add dynamic patcher problem handling

CHANGES.md, pyfakefs/fake_os.py, pyfakefs/tests/fake_os_test.py
=> Add missing follow_symlink argument to os.link

.github/workflows/testsuite.yml, CHANGES.md, pyfakefs/pytest_tests/pytest_fixture_test.py, pyfakefs/pytest_tests/pytest_reload_pandas_test.py, pyfakefs/pytest_tests/unhashable.py
- the module is not maintained and very trivial
- see #981
=> Remove the need to import the "undefined" module in test

CHANGES.md, pyfakefs/fake_filesystem.py, pyfakefs/tests/fake_os_test.py, pyfakefs/tests/fake_pathlib_test.py, pyfakefs/tests/test_utils.py
- umask is now applied per default
=> Fix handling of umask

CHANGES.md, docs/troubleshooting.rst, pyfakefs/fake_file.py, pyfakefs/fake_filesystem.py, pyfakefs/fake_os.py, pyfakefs/tests/fake_os_test.py
=> Add support for fake os.dup, os.dup2 and os.lseek

pyfakefs/fake_file.py, pyfakefs/fake_os.py, pyfakefs/tests/fake_os_test.py
=> Fixes for the last commits (os.dup / O_DIRECTORY)

.github/workflows/dockerfiles/Dockerfile_debian, .github/workflows/dockerfiles/Dockerfile_fedora, .github/workflows/dockerfiles/Dockerfile_redhat, .github/workflows/dockerfiles/Dockerfile_ubuntu, .github/workflows/testsuite.yml, Dockerfile
- may cause ID clashes in CI
Hopefully fixes failed CI for ubuntu.
=> Do not define the user ID in containers

.github/workflows/testsuite.yml
- disable pip version check to avoid annotation errors (see https://github.com/actions/setup-python/issues/809)
=> Add new pytest versions to CI

pyfakefs/fake_file.py, pyfakefs/fake_pathlib.py, pyfakefs/fake_scandir.py, pyfakefs/pytest_tests/io.py, pyfakefs/pytest_tests/pytest_doctest_test.py, pyfakefs/tests/dynamic_patch_test.py, pyfakefs/tests/example.py, pyfakefs/tests/fake_filesystem_shutil_test.py, pyfakefs/tests/fake_filesystem_vs_real_test.py, pyfakefs/tests/fake_open_test.py, pyfakefs/tests/fake_os_test.py, pyfakefs/tests/fake_pathlib_test.py, pyfakefs/tests/fake_stat_time_test.py, pyfakefs/tests/mox3_stubout_test.py
Discards rewrites of `io.open` based on feedback in #1020.
See #1020.
=> Run `pyupgrade --py37-plus`

CHANGES.md, pyfakefs/fake_filesystem_unittest.py, pyfakefs/tests/fake_filesystem_unittest_test.py
- fixes #1098 (regression in version 5.7.2)
=> Make sure tempfile is patched after resume

README.md, docs/intro.rst
- streamlined README
- moved section about testing to documentation
- mention conda install in documentation
=> Minor documentation updates
